export const VOID_ELEMENTS = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'param',
  'source',
  'track',
  'wbr',
])

export const EVENT_TYPES = new Set([
  'click',
  'dblclick',
  'change',
  'input',
  'keydown',
  'keyup',
  'keypress',
  'blur',
  'focus',
  'mousedown',
  'mouseup',
  'mouseover',
  'mouseout',
  'mousemove',
  'mouseenter',
  'mouseleave',
  'contextmenu',
  'submit',
  'scroll',
  'resize',
  'reset',
  'wheel',
  'touchstart',
  'touchmove',
  'touchend',
  'tap',
  'longTap',
  'swipeRight',
  'swipeUp',
  'swipeLeft',
  'swipeDown',
  'dragstart',
  'dragend',
  'dragover',
  'dragleave',
  'drop',
  'pointerdown',
  'pointerup',
  'pointermove',
  'pointerenter',
  'pointerleave',
  'pointerover',
  'pointerout',
  'pointercancel',
  'animationstart',
  'animationend',
  'animationiteration',
  'transitionstart',
  'transitionend',
  'transitionrun',
  'transitioncancel',
])

export const URL_ATTRIBUTES = new Set(['href', 'src', 'action'])

export const BOOLEAN_HTML_ATTRS = new Set([
  'disabled',
  'hidden',
  'readonly',
  'required',
  'checked',
  'selected',
  'multiple',
  'autofocus',
  'autoplay',
  'controls',
  'loop',
  'muted',
  'open',
  'novalidate',
  'formnovalidate',
  'defer',
  'async',
])

export const INTERNAL_PROPS = new Set(['key', 'ref', 'dangerouslySetInnerHTML'])
