import { resetUidCounter } from '@geajs/core'
import type { GeaComponentConstructor, StoreRegistry } from './types'
import { isInternalProp } from './types'

interface RestoreOptions {
  preserveNull?: boolean
}

export function restoreStoreState(
  registry: StoreRegistry,
  options?: RestoreOptions,
): void {
  if (typeof window === 'undefined') return
  const state = window.__GEA_STATE__
  if (!state || typeof state !== 'object') return

  for (const [name, storeInstance] of Object.entries(registry)) {
    const serialized = state[name]
    if (!serialized || typeof serialized !== 'object') continue
    for (const [key, value] of Object.entries(serialized)) {
      if (isInternalProp(key) || key === 'constructor' || key === '__proto__') continue
      try {
        // Don't overwrite client-initialized values with null from SSR,
        // unless preserveNull is set (for authoritative server nulls).
        if (value === null && storeInstance[key] != null && !options?.preserveNull) continue
        storeInstance[key] = value
      } catch {
        // Skip read-only properties
      }
    }
  }
}

export function hydrate(
  App: GeaComponentConstructor,
  element: HTMLElement | null,
  options?: { storeRegistry?: StoreRegistry },
): void {
  if (!element) {
    throw new Error('[gea-ssr] hydrate: target element not found')
  }

  // Auto-detect: if element has content, hydrate; otherwise fall back to render
  if (!element.hasChildNodes()) {
    const app = new App()
    if (typeof app.render === 'function') app.render(element)
    return
  }

  // Restore store state from server — silently, to prevent change notifications.
  // The DOM already reflects the server state; observer-driven reconciles would
  // duplicate list items because the tracking arrays aren't populated yet.
  if (options?.storeRegistry) {
    restoreStoreState(options.storeRegistry)
    // Discard any pending change notifications generated by restoreStoreState.
    // These are not real changes — they represent the initial SSR state that the
    // DOM already reflects. Without this, microtask-flushed observers would run
    // __refreshFilteredTodosItems (etc.) before __adoptListItems has populated
    // the tracking arrays, causing duplicate list items.
    for (const store of Object.values(options.storeRegistry)) {
      if (typeof (store as Record<string, unknown>).silent === 'function') {
        (store as Record<string, Function>).silent(() => { /* clears pending changes */ })
      }
    }
  }

  // Snapshot innerHTML before hydration for dev-mode mismatch detection
  const savedInnerHTML = (typeof import.meta !== 'undefined' && import.meta.env?.DEV)
    ? element.innerHTML
    : ''

  // Reset UID counter to match SSR-generated IDs so component IDs align with DOM
  resetUidCounter(0)

  // Hydration path — adopt existing DOM
  const app = new App()

  // Set the element to the existing DOM content
  app.element_ = element.firstElementChild
  app.rendered_ = true

  // Attach reactivity bindings (observers, events)
  if (typeof app.attachBindings_ === 'function') app.attachBindings_()
  if (typeof app.mountCompiledChildComponents_ === 'function') app.mountCompiledChildComponents_()
  if (typeof (app as Record<string, unknown>).__adoptListItems === 'function') (app as Record<string, Function>).__adoptListItems()
  if (typeof app.instantiateChildComponents_ === 'function') app.instantiateChildComponents_()
  if (typeof app.setupEventDirectives_ === 'function') app.setupEventDirectives_()
  if (typeof app.onAfterRender === 'function') app.onAfterRender()
  if (typeof app.onAfterRenderHooks === 'function') app.onAfterRenderHooks()

  // Dev-mode hydration mismatch detection — runs AFTER hydration is fully complete
  // Uses setTimeout to ensure all lifecycle hooks have finished before re-rendering
  // Uses dynamic import() to avoid pulling server code into client bundle
  if (typeof import.meta !== 'undefined' && import.meta.env?.DEV) {
    setTimeout(async () => {
      try {
        const [{ renderToString }, { detectHydrationMismatch }] = await Promise.all([
          import('./render'),
          import('./mismatch'),
        ])
        resetUidCounter(0)  // Safe: hydration is complete
        const clientHtml = renderToString(App)
        const mismatch = detectHydrationMismatch(
          { innerHTML: savedInnerHTML },
          clientHtml,
        )
        if (mismatch) {
          console.warn(
            '[gea-ssr] Hydration mismatch detected.\n' +
            'Server HTML: ' + mismatch.server.substring(0, 200) + '\n' +
            'Client HTML: ' + mismatch.client.substring(0, 200),
          )
        }
      } catch {
        // Silently skip mismatch detection if imports fail
      }
    }, 0)
  }

}
